name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        id: changelog
        shell: bash
        run: |
          # Get previous tag
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "")

          # Generate changelog content
          if [ -z "$PREV_TAG" ]; then
            CHANGELOG="## Changes"$'\n'"$(git log --pretty=format:"- %s (%h)")"
          else
            CHANGELOG="## Changes since $PREV_TAG"$'\n'"$(git log "$PREV_TAG"..HEAD --pretty=format:"- %s (%h)")"
          fi

          # Output changelog safely using printf
          printf "changelog<<EOF\n%s\nEOF\n" "$CHANGELOG" >> "$GITHUB_OUTPUT"

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "${{ steps.changelog.outputs.changelog }}"

